import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Nav from "@/components/Nav";
import { montserrat } from "@/components/ui/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className="bg-[#0E0C38]">
          <Nav />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
